---
- name: Install apache on Rocky and Ubuntu
  hosts: all
  tasks:
    - name: Install Apache2 on Ubuntu
      ansible.builtin.apt:
        name: Apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: Install Httpd on Rocky
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"
