---
- name: Multiple conditions
  hosts: rocky
  tasks:
    - name: Install httpd on Rocky when memory 300 MB free
      ansible.builtin.yum:
        name: httpd
        state: present
      when: >
        ansible_facts['os_family'] == "RedHat"
        and ansible_facts['memory_mb']['real']['free'] > 300
    - name: Configure service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
