# exercise: 7-2
---
- name: Use loop and condition
  hosts: rocky
  tasks:
    - name: Check HTTPD service and restart sshd
      ansible.builtin.command:
        cmd: systemctl is-active httpd
      register: service_status
      ignore_errors: true
    # - ansible.builtin.debug:
    #     var: service_status.rc
    - name: Restart SSHD if httpd service is stopped
      ansible.builtin.service:
        name: sshd
        state: restarted
      when: service_status.rc == 0
      # when: service_status.stdout.find != 3
