---
- name: Check available memory and do something
  hosts: rocky
  tasks:
    - name: Check if available memory is above 500 mb
      ansible.builtin.debug:
        msg: "Disks space for the {{ item.mount }} is {{ item.size_available/ (1024*1024) }} MBytes"
      when: item.mount == "/"
      loop: "{{ ansible_facts['mounts'] }}"
