# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.linked_clone = true
  end
  # application server 01
  config.vm.define "appie01" do |app1|
    app1.vm.hostname = "appie01.pansible.de"
    app1.vm.network :private_network, ip: "192.168.56.10", hostname: true
  end
  # application server 02
  config.vm.define "appie02" do |app2|
    app2.vm.hostname = "appie02.pansible.de"
    app2.vm.network :private_network, ip: "192.168.56.11", hostname: true
  end
  # application server 03
  config.vm.define "appie03" do |app2|
    app2.vm.hostname = "appie03.pansible.de"
    app2.vm.network :private_network, ip: "192.168.56.12", hostname: true
  end
end
