---
- name: Install firewall, mariadb and vsftp
  hosts: rocky
  vars_files:
    - allvars.yaml
  tasks:
    - name: Install packages
      ansible.builtin.yum:
        name:
          - "{{ ansible_facts['ansible_local']['packages']['packages']['db_package'] }}"
          - "{{ ansible_facts['ansible_local']['packages']['packages']['firewall_package'] }}"
          - "{{ ansible_facts['ansible_local']['packages']['packages']['ftp_package'] }}"
          - "{{ ansible_facts['ansible_local']['packages']['packages']['smb_package'] }}"
          - "{{ ansible_facts['ansible_local']['packages']['packages']['web_package'] }}"
        state: present
    - name: Configure smb service
      ansible.builtin.service:
        name: "{{ ansible_facts['ansible_local']['services']['services']['smb_service'] }}"
        enabled: true
        state: started
    - name: Configure vsftp service
      ansible.builtin.service:
        name: "{{ ansible_facts['ansible_local']['services']['services']['ftp_service'] }}"
        enabled: true
        state: started
    - name: Configure mariadb service
      ansible.builtin.service:
        name: "{{ ansible_facts['ansible_local']['services']['services']['db_service'] }}"
        enabled: true
        state: started
    - name: Configure firewalld service
      ansible.builtin.service:
        name: "{{ ansible_facts['ansible_local']['services']['services']['firewall_service'] }}"
        enabled: true
        state: started
    - name: Configure Httpd service
      ansible.builtin.service:
        name: "{{ ansible_facts['ansible_local']['services']['services']['web_service'] }}"
        enabled: true
        state: started
    - name: Allow Firewall port 80
      ansible.posix.firewalld:
        immediate: true
        permanent: true
        service: http
        state: enabled
    - name: Create a custom welcome page
      ansible.builtin.copy:
        content: >
          <h1> Welcome to the
          Ansible Web Server
          </h1>
        dest: "{{ web_root }}/index.html"
        group: root
        owner: root
        mode: "0644"
- name: Check web page is available from your workstation
  hosts: localhost
  become: false
  tasks:
    - name: Check Web Page
      ansible.builtin.uri:
        url: http://192.168.56.50
        return_content: true
        status_code: 200
