# simple play to demo some command change nothing,
# the report status as changed.
# Date: 22-12-2023
---
- name: Check the date on a system
  hosts: rocky
  tasks:
    - name: Check the date using command module
      ansible.builtin.command:
        cmd: date
      register: date_status
      changed_when: false
    - name: Print date
      ansible.builtin.debug:
        var: date_status.stdout
