# advance version of the loop and the one i like a lot
---
- name: Advance version of 101 loop
  hosts: rocky
  vars:
    services:
      - vsftpd
      - httpd
      - smb
  tasks:
    - name: Install packages
      ansible.builtin.yum:
        name:
          - vsftpd
          - httpd
          - samba
        state: present
    - name: Configure services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ services }}"
