# This playbook deal with handling failures using force_handlers
# I used reboot module.
---
- name: Uninstall httpd and reboot hosts
  hosts: rocky
  force_handlers: true
  tasks:
    - name: Uninstall httpd
      ansible.builtin.yum:
        name: httpd
        state: absent
      notify: Reboot_Host
  handlers:
    - name: Reboot_Host
      ansible.builtin.reboot:
        msg: "Updating kernel and reboot is required in 60 seconds"
        pre_reboot_delay: 60
        post_reboot_delay: 180
        reboot_timeout: 600
        connect_timeout: 5
        test_command: whoami
