# use 'custom' facts to deploy httpd
- name: Install httpd
  hosts: rocky
  tasks:
    - name: Install the package
      ansible.builtin.yum:
        name: "{{ ansible_facts['ansible_local']['custom']['software']['package'] }}"
        state: present
    - name: Configure service
      ansible.builtin.service:
        name: "{{ ansible_facts['ansible_local']['custom']['software']['service'] }}"
        enabled: "{{ ansible_facts['ansible_local']['custom']['software']['enable'] }}"
        state: "{{ ansible_facts['ansible_local']['custom']['software']['state'] }}"
    
